// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IAkarIcons:moonFill': typeof import('~icons/akar-icons/moon-fill')['default']
    'IAkarIcons:sunFill': typeof import('~icons/akar-icons/sun-fill')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
  }
}

export { }
